name: Meson Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Meson Build
       run: meson setup build
     - name: compile vector
       run: | 
         pushd build
         ninja
         popd
          
  
